### ISSUE TITLE
Use annotated tag instead of lightweight tag?

### ISSUE THREAD

**Issue by eight04** [dylanpyle/version#21]
Annotated tags store more information and it is easier to push annotated tags via `git push --follow-tags`

**Comment by dylanpyle** [comment]
@eight04 seems like a great idea! 

I can't think of any backwards incompatibility issues this would introduce (i.e. breaking any workflows that rely on these tags being lightweight), would you anticipate any?

Should be as simple as adding another flag & message [here](https://github.com/dylanpyle/version/blob/main/git.ts#L49); I'll get to it when I have a chance, but if you or someone else beats me to it I'll happy merge & release a PR.

**Comment by dylanpyle** [comment]
Fixed in v1.2.0 🙂
