### ISSUE TITLE
The git tag created should be prefaced with `v`

### ISSUE THREAD

**Issue by justinmchase** [dylanpyle/version#6]
I like that the version in the file is just the number, that seems right but when generating a git tag that should be generated with the common `v` standard.

e.g.
```sh
$ version init
$ git tag
v0.1.0
$ version get
0.1.0
```

**Comment by dylanpyle** [comment]
I'm cool with this, especially since that's what npm does.

**Comment by dylanpyle** [comment]
Fixed in #9!

**Comment by dylanpyle** [comment]
released in v1.1.0 which arguably could have been considered a breaking change but 🤷
